name: Deploy Fake
on:
  repository_dispatch:
    types: [ remote-deploy ]
jobs:
  deploy-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy in the environment
        run: echo "Deploying to the environment ${{ github.event.client_payload.environment }}"